### ISSUE TITLE
Is it possible to add an exception for the Distill Web Monitor addon?

### ISSUE THREAD

**Issue by hiasl360** [Reeywhaar/holdtab#3]
Distill web monitor checks periodically websites for changes in the background.
With holdtab enabled the opened tab from Distill Web Monitor can't load completly.
I tested it with the load tab on select addon and distill web monitor works.
Load tab on select doesn't work for me because it can't handle file uri properly.

**Comment by reeywhaar** [comment]
Dear @hiasl360, I’ll check it out once I am at home. Thank you for report!

**Comment by reeywhaar** [comment]
@hiasl360 I get your point, I think I'll exclude all "moz-extension" urls from being holded.

**Comment by reeywhaar** [comment]
Oh, no, I see, problem is a bit more complicated

**Comment by reeywhaar** [comment]
@hiasl360 I excluded all non http(s) tabs from being holded, which also solves your problem with DistillWebMonitor. Right now extension is in beta phase, so I could test that I didn't make some stupid mistake. You can test it as well at https://addons.mozilla.org/en-US/firefox/addon/holdtab/#beta-channel or wait for about a week, when I make it to public. Thank you!
